// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-transactions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "Listar lan\xE7amentos",
  description: "Lista os lan\xE7amentos financeiros (despesas, receitas, investimentos) do usu\xE1rio autenticado. Aceita filtros opcionais por intervalo de datas, tipo e categoria.",
  inputSchema: {
    data_inicio: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data inicial no formato YYYY-MM-DD."),
    data_fim: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data final no formato YYYY-MM-DD."),
    tipo: z.enum(["despesa", "receita", "investimento"]).optional(),
    categoria: z.string().optional().describe("Filtrar por nome exato de categoria."),
    limit: z.number().int().min(1).max(500).optional().describe("M\xE1ximo de registros (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ data_inicio, data_fim, tipo, categoria, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = sb(ctx).from("lancamentos").select("id,data,categoria,valor,parcelas,quem_gastou,descricao,tipo,ganhos,cartao_id,conta_id").order("data", { ascending: false }).limit(limit ?? 100);
    if (data_inicio) q = q.gte("data", data_inicio);
    if (data_fim) q = q.lte("data", data_fim);
    if (tipo) q = q.eq("tipo", tipo);
    if (categoria) q = q.eq("categoria", categoria);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { transacoes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_transaction_default = defineTool2({
  name: "create_transaction",
  title: "Criar lan\xE7amento",
  description: "Cria um novo lan\xE7amento financeiro para o usu\xE1rio autenticado. Despesas devem ter valor negativo; receitas e investimentos positivos.",
  inputSchema: {
    data: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data do lan\xE7amento no formato YYYY-MM-DD."),
    categoria: z2.string().min(1).describe("Nome da categoria (deve existir em list_categories)."),
    valor: z2.number().describe("Valor em reais. Despesas devem ser negativas."),
    tipo: z2.enum(["despesa", "receita", "investimento"]),
    descricao: z2.string().optional(),
    parcelas: z2.number().int().min(1).max(60).optional().describe("N\xFAmero de parcelas (padr\xE3o 1)."),
    quem_gastou: z2.string().optional(),
    cartao_id: z2.string().uuid().optional(),
    conta_id: z2.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("lancamentos").insert({
      usuario_id: ctx.getUserId(),
      data: input.data,
      categoria: input.categoria,
      valor: input.valor,
      tipo: input.tipo,
      descricao: input.descricao ?? null,
      parcelas: input.parcelas ?? 1,
      quem_gastou: input.quem_gastou ?? null,
      cartao_id: input.cartao_id ?? null,
      conta_id: input.conta_id ?? null,
      ganhos: 0
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Lan\xE7amento criado: ${data.id}` }],
      structuredContent: { lancamento: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Listar categorias",
  description: "Lista as categorias ativas do usu\xE1rio com seus or\xE7amentos.",
  inputSchema: {
    tipo: z3.enum(["despesa", "receita", "investimento"]).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ tipo }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = sb3(ctx).from("categorias").select("id,nome,tipo,orcamento,ordem,ativa").eq("ativa", true).order("ordem");
    if (tipo) q = q.eq("tipo", tipo);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { categorias: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-accounts.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
function sb4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_accounts_default = defineTool4({
  name: "list_accounts",
  title: "Listar contas banc\xE1rias",
  description: "Lista as contas banc\xE1rias ativas do usu\xE1rio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("contas_bancarias").select("*").eq("ativo", true);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { contas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-cards.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
function sb5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_cards_default = defineTool5({
  name: "list_credit_cards",
  title: "Listar cart\xF5es de cr\xE9dito",
  description: "Lista os cart\xF5es de cr\xE9dito ativos do usu\xE1rio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await sb5(ctx).from("cartoes_credito").select("*").eq("ativo", true);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { cartoes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-goals.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
function sb6(ctx) {
  return createClient6(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_goals_default = defineTool6({
  name: "list_goals",
  title: "Listar metas & reservas",
  description: "Lista as metas financeiras (reservas, viagens, compras) do usu\xE1rio com o total aportado em cada uma.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const client = sb6(ctx);
    const { data: metas, error } = await client.from("metas_financeiras").select("*").order("ordem");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = (metas ?? []).map((m) => m.id);
    const aportesPor = {};
    if (ids.length > 0) {
      const { data: aportes } = await client.from("metas_aportes").select("meta_id,valor").in("meta_id", ids);
      for (const a of aportes ?? []) {
        aportesPor[a.meta_id] = (aportesPor[a.meta_id] ?? 0) + Number(a.valor);
      }
    }
    const enriched = (metas ?? []).map((m) => ({
      ...m,
      total_aportado: Number(m.valor_inicial ?? 0) + (aportesPor[m.id] ?? 0)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(enriched) }],
      structuredContent: { metas: enriched }
    };
  }
});

// src/lib/mcp/tools/cycle-summary.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function sb7(ctx) {
  return createClient7(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function calcularCiclo(diaInicio, ref) {
  const ano = ref.getFullYear();
  const mes = ref.getMonth();
  const dia = ref.getDate();
  let inicioMes = mes;
  let inicioAno = ano;
  if (dia < diaInicio) {
    inicioMes = mes - 1;
    if (inicioMes < 0) {
      inicioMes = 11;
      inicioAno -= 1;
    }
  }
  const inicio = new Date(inicioAno, inicioMes, diaInicio);
  const fim = new Date(inicioAno, inicioMes + 1, diaInicio - 1);
  const fmt = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  return { inicio: fmt(inicio), fim: fmt(fim) };
}
var cycle_summary_default = defineTool7({
  name: "cycle_summary",
  title: "Resumo do ciclo",
  description: "Retorna o resumo financeiro do ciclo atual (ou de uma data de refer\xEAncia): total de receitas, despesas, investimentos e saldo.",
  inputSchema: {
    data_referencia: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data dentro do ciclo desejado. Padr\xE3o: hoje.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ data_referencia }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const client = sb7(ctx);
    const { data: prefs } = await client.from("user_preferences").select("cycle_start_day").eq("usuario_id", ctx.getUserId()).maybeSingle();
    const diaInicio = prefs?.cycle_start_day ?? 25;
    const ref = data_referencia ? /* @__PURE__ */ new Date(data_referencia + "T12:00:00") : /* @__PURE__ */ new Date();
    const ciclo = calcularCiclo(diaInicio, ref);
    const { data, error } = await client.from("lancamentos").select("valor,tipo,ganhos").gte("data", ciclo.inicio).lte("data", ciclo.fim);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let receitas = 0;
    let despesas = 0;
    let investimentos = 0;
    let ganhos = 0;
    for (const t of data ?? []) {
      const v = Number(t.valor);
      if (t.tipo === "receita") receitas += v;
      else if (t.tipo === "despesa") despesas += Math.abs(v);
      else if (t.tipo === "investimento") investimentos += v;
      ganhos += Number(t.ganhos ?? 0);
    }
    const saldo = receitas - despesas - investimentos + ganhos;
    const resumo = {
      ciclo,
      total_receitas: receitas,
      total_despesas: despesas,
      total_investimentos: investimentos,
      total_ganhos: ganhos,
      saldo
    };
    return {
      content: [{ type: "text", text: JSON.stringify(resumo, null, 2) }],
      structuredContent: resumo
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eepkixxqvelppxzfwoin";
var mcp_default = defineMcp({
  name: "plenna-mcp",
  title: "Plenna Finan\xE7as",
  version: "0.1.0",
  instructions: "Ferramentas para consultar e registrar dados financeiros do usu\xE1rio no Plenna: lan\xE7amentos, categorias, contas banc\xE1rias, cart\xF5es de cr\xE9dito, metas & reservas e resumo do ciclo atual. Despesas s\xE3o armazenadas com valor negativo. O ciclo financeiro do usu\xE1rio come\xE7a no dia definido em prefer\xEAncias (padr\xE3o 25).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_transactions_default,
    create_transaction_default,
    list_categories_default,
    list_accounts_default,
    list_cards_default,
    list_goals_default,
    cycle_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
